version: '3'
services:
  app:
    build:
      context: .
    depends_on:
      - db
    command: poetry run pytest ./tests --cache-clear

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5454:5432"
